src/UserInterface/Models/ErrorViewModel.cs
namespace UserInterface.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/UserInterface/Controllers/ConfigurationItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Domain.Entities;
using System.Text;

namespace UserInterface.Controllers
{
    public class ConfigurationItemsController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public ConfigurationItemsController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"https://localhost:44308/api/Configuration/all");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ConfigurationItem>>(jsonData);
                return View(values);
            }
            return View();
        }

        [HttpGet]
        public IActionResult CreateConfiguration()
        {
            var model = new ConfigurationItem();
            model.Id = Guid.NewGuid().ToString();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateConfiguration(ConfigurationItem configurationModel)
        {
            
            if (ModelState.IsValid)
            {
                var jsonData = JsonConvert.SerializeObject(configurationModel);
                StringContent content = new StringContent(jsonData, Encoding.UTF8, "application/json");

                var client = _httpClientFactory.CreateClient();
                var responseMessage = await client.PostAsync("https://localhost:44308/api/Configuration", content);

                if (responseMessage.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> UpdateConfiguration([FromRoute] string id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"https://localhost:44308/api/Configuration/{id}");

            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var value = JsonConvert.DeserializeObject<ConfigurationItem>(jsonData);
                return View(value);
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> UpdateConfiguration(ConfigurationItem configurationModel)
        {
            var jsonData = JsonConvert.SerializeObject(configurationModel);
            StringContent content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.PutAsync("https://localhost:44308/api/Configuration", content);

            if (responseMessage.IsSuccessStatusCode)
                return RedirectToAction("Index");

            return View();
        }


        [HttpGet]
        public async Task<IActionResult> DeleteConfiguration([FromRoute] string id)
        {
       
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.DeleteAsync($"https://localhost:44308/api/Configuration/{id}");

            if (responseMessage.IsSuccessStatusCode)
                return RedirectToAction("Index");

            return View();
        }

    }
}

src/UserInterface/Views/ConfigurationItems/CreateConfiguration.cshtml
@model Domain.Entities.ConfigurationItem

@{
    ViewData["Title"] = "CreateConfiguration";
   
}

<h1>Create Configuration</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateConfiguration" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden"/>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control">
                    <option selected>Open this select menu</option>
                    <option value="String">String</option>
                    <option value="Bool">Bool</option>
                    <option value="Int">Int</option>
                    <option value="Double">Double</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationName" class="control-label"></label>
                <input asp-for="ApplicationName" class="form-control" />
                <span asp-validation-for="ApplicationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/UserInterface/Views/ConfigurationItems/DeleteConfiguration.cshtml
@model Domain.Entities.ConfigurationItem

@{
    ViewData["Title"] = "DeleteConfiguration";
}

<h1>Delete Configuration</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DeleteConfigurations" method="delete">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control">
                    <option selected>Open this select menu</option>
                    <option value="String">String</option>
                    <option value="Bool">Bool</option>
                    <option value="Int">Int</option>
                    <option value="Double">Double</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationName" class="control-label"></label>
                <input asp-for="ApplicationName" class="form-control" />
                <span asp-validation-for="ApplicationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/UserInterface/Views/ConfigurationItems/Index.cshtml
@model IEnumerable<Domain.Entities.ConfigurationItem>

@{
    ViewData["Title"] = "Index";
}

<h2>Configuration List</h2>

<p>
    <a asp-action="CreateConfiguration">Create New Configuration</a>
    <br />
    <br />

    <input type="text" id="searchInput" placeholder="Search by Name">
    <br />

</p>
<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                
                <td>
                    <span style="font-weight: bold; color:black">@item.Name</span>
                </td>
                <td>
                    <span style="font-weight: bold; color:black">@item.Type</span>
                </td>
                <td>
                    <span style="font-weight: bold; color:black">@item.Value</span>
                </td>
                <td>
                    @if (item.IsActive)
                    {
                        <span style="font-weight: bold; color: green;">Aktif</span>
                    }
                    else
                    {
                        <span style="font-weight: bold; color: red;">Pasif</span>
                    }
                </td>
                <td>
                    <span style="font-weight: bold; color:black">@item.ApplicationName</span>
                </td>
                <td>
                    <a asp-controller="ConfigurationItems" asp-action="UpdateConfiguration" asp-route-id="@item.Id" type="button" class="btn btn-dark">
                        Update
                    </a>

          @*           <a asp-controller="ConfigurationItems" asp-action="DeleteConfiguration" asp-route-id="@item.Id" type="button" class="btn btn-danger">
                        Delete
                    </a> *@


                    <a asp-controller="ConfigurationItems" asp-action="DeleteConfiguration" asp-route-id="@item.Id" type="button" class="btn btn-danger">
                        Delete
                    </a>



                    


                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    
    const searchInput = document.getElementById('searchInput');
    const tableRows = document.querySelectorAll('tbody tr');



    
    searchInput.addEventListener('input', function () {
        const searchText = this.value.toLowerCase();

       
        tableRows.forEach(row => {
            const nameColumnText = row.querySelector('td:nth-child(1)').textContent.toLowerCase();
            if (nameColumnText.includes(searchText)) {
                row.style.display = 'table-row';
            } else {
                row.style.display = 'none';
            }
        });
    });
</script>

src/UserInterface/Views/ConfigurationItems/UpdateConfiguration.cshtml
@model Domain.Entities.ConfigurationItem

@{
    ViewData["Title"] = "UpdateConfiguration";
}

<h1>Update Configuration</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateConfiguration" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control">
                    <option selected>Open this select menu</option>
                    <option value="String">String</option>
                    <option value="Bool">Bool</option>
                    <option value="Int">Int</option>
                    <option value="Double">Double</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationName" class="control-label"></label>
                <input asp-for="ApplicationName" class="form-control" />
                <span asp-validation-for="ApplicationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/UserInterface/Views/Shared/Components/_AdminFooterLayoutComponentPartial/Default.cshtml
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6" >
                2024 © <a href="" style="color:black" target="_blank">SecilMvc</a>
            </div>
            <div class="col-sm-6">
                <div class="text-sm-right d-none d-sm-block" >
                    Develop By<a href="https://github.com/ali-aslan" style="color:forestgreen" target="_blank"> Ali ASLAN</a>
                </div>
            </div>
        </div>
    </div>
</footer>

src/UserInterface/Views/Shared/Components/_AdminHeaderLayoutComponentPartial/Default.cshtml
<head>
    <meta charset="utf-8" />
    <title>Secil Backend Case</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="MyraStudio" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    
    <link rel="shortcut icon" href="assets/images/favicon.ico">

    
    <link href="~/admin-area/plugins/datatables/dataTables.bootstrap4.css" rel="stylesheet" type="text/css" />
    <link href="~/admin-area/plugins/datatables/responsive.bootstrap4.css" rel="stylesheet" type="text/css" />
    <link href="~/admin-area/plugins/datatables/buttons.bootstrap4.css" rel="stylesheet" type="text/css" />
    <link href="~/admin-area/plugins/datatables/select.bootstrap4.css" rel="stylesheet" type="text/css" />

    <link href="~/admin-area/plugins/bootstrap-touchspin/jquery.bootstrap-touchspin.css" rel="stylesheet" type="text/css" />
    <link href="~/admin-area/plugins/daterangepicker/daterangepicker.css" rel="stylesheet" type="text/css" />
    <link href="~/admin-area/plugins/select2/select2.min.css" rel="stylesheet" type="text/css" />
    <link href="~/admin-area/plugins/switchery/switchery.min.css" rel="stylesheet" type="text/css" />
    <link href="~/admin-area/plugins/bootstrap-colorpicker/bootstrap-colorpicker.min.css" rel="stylesheet" type="text/css" />
    <link href="~/admin-area/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />

   
    <link href="~/admin-area/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/admin-area/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/admin-area/assets/css/theme.min.css" rel="stylesheet" type="text/css" />




</head>

src/UserInterface/Views/Shared/Components/_AdminScriptLayoutComponentPartial/Default.cshtml
<div class="menu-overlay"></div>

<!-- jQuery  -->
<script src="~/admin-area/assets/js/jquery.min.js"></script>
<script src="~/admin-area/assets/js/bootstrap.bundle.min.js"></script>
<script src="~/admin-area/assets/js/metismenu.min.js"></script>
<script src="~/admin-area/assets/js/waves.js"></script>
<script src="~/admin-area/assets/js/simplebar.min.js"></script>

<!-- plugins js -->
<script src="~/admin-area/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/admin-area/plugins/datatables/dataTables.bootstrap4.js"></script>
<script src="~/admin-area/plugins/datatables/dataTables.responsive.min.js"></script>
<script src="~/admin-area/plugins/datatables/responsive.bootstrap4.min.js"></script>
<script src="~/admin-area/plugins/datatables/dataTables.buttons.min.js"></script>
<script src="~/admin-area/plugins/datatables/buttons.bootstrap4.min.js"></script>
<script src="~/admin-area/plugins/datatables/buttons.html5.min.js"></script>
<script src="~/admin-area/plugins/datatables/buttons.flash.min.js"></script>
<script src="~/admin-area/plugins/datatables/buttons.print.min.js"></script>
<script src="~/admin-area/plugins/datatables/dataTables.keyTable.min.js"></script>
<script src="~/admin-area/plugins/datatables/dataTables.select.min.js"></script>
<script src="~/admin-area/plugins/datatables/pdfmake.min.js"></script>
<script src="~/admin-area/plugins/datatables/vfs_fonts.js"></script>
<script src="~/admin-area/plugins/autonumeric/autoNumeric-min.js"></script>
<!-- third party js ends -->

<!-- Datatables init -->
<script src="~/admin-area/assets/pages/datatables-demo.js"></script>

<!-- App js -->
<script src="~/admin-area/assets/js/theme.js"></script>

<!-- select -->
<script src="~/admin-area/plugins/select2/select2.min.js"></script>

<!-- Morris Js-->
<script src="~/admin-area/plugins/morris-js/morris.min.js"></script>
<!-- Raphael Js-->
<script src="~/admin-area/plugins/raphael/raphael.min.js"></script>

<!-- Morris Custom Js-->
<script src="~/admin-area/assets/pages/dashboard-demo.js"></script>


<script src="~/admin-area/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<script src="~/admin-area/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
<script src="~/admin-area/plugins/moment/moment.js"></script>
<script src="~/admin-area/plugins/daterangepicker/daterangepicker.js"></script>
<script src="~/admin-area/plugins/switchery/switchery.min.js"></script>
<script src="~/admin-area/plugins/bootstrap-colorpicker/bootstrap-colorpicker.min.js"></script>
<script src="~/admin-area/plugins/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
<script src="~/admin-area/assets/pages/advanced-plugins-demo.js"></script>
<script src="~/js/site.js"></script>

src/UserInterface/Views/Shared/Components/_AdminSidebarLayoutComponentPartial/Default.cshtml
    <div class="vertical-menu">

        <div data-simplebar class="h-100">

            <div class="navbar-brand-box">
                <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="logo">
                    <span>
                    Secil Backend Case
                    </span>
                </a>
            </div>

            <div id="sidebar-menu">
                <ul class="metismenu list-unstyled" id="side-menu">
                    <li class="menu-title">Menu</li>
                    <li>
                    <a asp-area="" asp-controller="ConfigurationItems" asp-action="CreateConfiguration" class="waves-effect"><i class="fas fa-plus"></i><span>Add Configuration</span></a>
                    </li>
                    <li>
                    <a asp-area="" asp-controller="ConfigurationItems" asp-route-applicationName="string" asp-action="Index" class="waves-effect"><i class="mdi mdi-format-list-bulleted-square"></i><span>Configurations List</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

src/UserInterface/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

@await Component.InvokeAsync("_AdminHeaderLayoutComponentPartial")

<body>

    <div id="layout-wrapper">

       
        @await Component.InvokeAsync("_AdminSidebarLayoutComponentPartial")

        <div class="main-content">
            <div class="page-content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
            @await Component.InvokeAsync("_AdminFooterLayoutComponentPartial")

        </div>
    </div>

    @await Component.InvokeAsync("_AdminScriptLayoutComponentPartial")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/UserInterface/Views/Shared/_Notification.cshtml
@if (TempData["info"] is not null)
{
    <div class="alert alert-info my-5" role="alert">
        @TempData["info"]
    </div>
}

@if (TempData["success"] is not null)
{
    <div class="alert alert-success my-5" role="alert">
        @TempData["success"]
    </div>
}

@if (TempData["danger"] is not null)
{
    <div class="alert alert-danger my-5" role="alert">
        @TempData["danger"]
    </div>
}